id = "kulala"
name = "Kulala"
description = "A port of kulala.nvim for Zed"
version = "0.1.0"
schema_version = 1
authors = ["A23187 <a23187.1979421048@gmail.com>"]
repository = "https://github.com/A-23187/zed-kulala"

[grammars.kulala_http]
repository = "https://github.com/mistweaverco/kulala.nvim"
rev = "5d3916195a97928b8f9b79d96029f37d19ba866d"
path = "lua/tree-sitter"

[language_servers.kulala-ls]
name = "Kulala Language Server"
languages = ["Kulala HTTP"]
