name = "Kulala HTTP"
grammar = "kulala_http"
path_suffixes = ["http", "rest"]
line_comments = ["# "]
brackets = [
    { start = "{%", end = "%}", close = true, newline = true },
    { start = "{{", end = "}}", close = true, newline = false },
]
